#pragma once

#include "NativeGameplayTags.h"

namespace SurvivalGameplayTags
{
	SUNRISEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resource_Food);
	SUNRISEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resource_Wood);
	SUNRISEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resource_Stone);
	SUNRISEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resource_Metal);
	SUNRISEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Building_MainBase);
	SUNRISEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Building_Barracks);
	SUNRISEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Building_House);
	SUNRISEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Building_Defense);
	SUNRISEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Worker);
} // namespace SurvivalGameplayTags
