#pragma once

#include "NativeGameplayTags.h"

namespace SunrisePawnTags
{
	SUNRISEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Class_Swordsman);
	SUNRISEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Class_Archer);
	SUNRISEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Class_Healer);
	SUNRISEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Class_Mage);
	SUNRISEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Class_Vanguard);
	SUNRISEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Kind_Creep);
	SUNRISEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Kind_Hero);
	SUNRISEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Kind_Summoned);
	SUNRISEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_DamageDealer);
	SUNRISEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Frontline);
	SUNRISEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Support);
} // namespace SunrisePawnTags
